version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Test123
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=auth_db,core_db
    ports:
      - 5433:5432
    volumes:
      - /var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  auth-service:
    build: "./auth"
    volumes:
      - ./auth:/home/node/app
      - staticfiles:/home/node/app/src/public
      - /home/node/app/node_modules/
    depends_on:
      - db
      - rabbitmq
    environment:
      - "BASE_URL=https://api.tenanttopia.pl"
      - DB_USERNAME=postgres
      - DB_PASSWORD=Test123
      - DB_DATABASE=auth_db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_TYPE=pg
      - PORT=3333
      - "RABBITMQ_URL=amqp://rabbitmq:5672"

  core-service:
    build: "./core"
    volumes:
      - ./core:/home/node/app
      - /home/node/app/node_modules/
    depends_on:
      - db
      - rabbitmq
    environment:
      - "BASE_URL=https://api.tenanttopia.pl"
      - DB_USERNAME=postgres
      - DB_PASSWORD=Test123
      - DB_HOST=db
      - DB_DATABASE=core_db
      - DB_PORT=5432
      - DB_TYPE=pg
      - PORT=3333
      - "RABBITMQ_URL=amqp://rabbitmq:5672"

  messaging-service:
    build: "./messaging"
    volumes:
      - ./messaging:/home/node/app
      - /home/node/app/node_modules/
    depends_on:
      - db
      - rabbitmq
    environment:
      - "RABBITMQ_URL=amqp://rabbitmq:5672"

  nginx:
    build: ./nginx
    depends_on:
      - auth-service
      - core-service
    ports:
      - 8080:80
    volumes:
      - staticfiles:/static

volumes:
  staticfiles:
