env:
  commonjs: true
  es2020: true
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
